export default {
  products: [
    {
      "id": "1",
      "name": "Call of Duty: Black Ops Cold War",
      "serNum": "978729204",
      "price": 57.99,
      "manufacturer": "Activision",
      "category": "Playstation 5",
      "quantity": 10,
      "cartQuantity": 1,
      "image": "/assets/COD.jpg",
      "description": " The iconic Black Ops series is back with Call of Duty®: Black Ops Cold War - the direct sequel to the original and fan-favorite Call of Duty®: Black Ops. Black Ops Cold War will drop fans into the depths of the Cold War’s volatile geopolitical battle of the early 1980s. Nothing is ever as it seems in a gripping single-player Campaign, where players will come face-to-face with historical figures and hard truths, as they battle around the globe through iconic locales like East Berlin, Vietnam, Turkey, Soviet KGB headquarters and more.<br>As elite operatives, you will follow the trail of a shadowy figure named Perseus who is on a mission to destabilize the global balance of power and change the course of history.Descend into the dark center of this global conspiracy alongside iconic characters Woods, Mason and Hudson and a new cast of operatives attempting to stop a plot decades in the making.",
      "inStock": 10,
      "filtered": 10
    },
    {
      "id": "2",
      "name": "Marvel's Spider-Man: Miles Morales",
      "serNum": "505188322",
      "price": 49.99,
      "manufacturer": "Sony",
      "category": "Playstation 5",
      "quantity": 15,
      "cartQuantity": 1,
      "image": "/assets/spiderman.jpg",
      "inStock": 0,
      "filtered": 10
    },
    {
      "id": "3",
      "name": "Borderland 3",
      "serNum": "694640798",
      "price": 55.79,
      "manufacturer": "2K",
      "category": "XboxOne",
      "quantity": 10,
      "cartQuantity": 1,
      "image": "/assets/borderland3.jpg",
      "inStock": 8,
      "filtered": 10
    },
    {
      "id": "4",
      "name": "NBA 2K21",
      "serNum": "615786259",
      "price": 55.09,
      "manufacturer": "2K Games",
      "category": "Playstation 5",
      "quantity": 26,
      "cartQuantity": 1,
      "image": "/assets/nba2k21.jpg",
      "inStock": 10,
      "filtered": 10
    },
    {
      "id": "5",
      "name": "Cyberpunk 2077",
      "serNum": "978421361",
      "price": 56.95,
      "manufacturer": "CD Projekt RED",
      "category": "XboxOne",
      "quantity": 10,
      "cartQuantity": 1,
      "image": "/assets/Cyberpunk2077.jpg",
      "inStock": 10,
      "filtered": 10
    },
    {
      "id": "6",
      "name": "Gears 5",
      "serNum": "193958478",
      "price": 59.79,
      "manufacturer": "Microsoft",
      "category": "XboxOne",
      "quantity": 10,
      "cartQuantity": 1,
      "image": "/assets/gears5.jpg",
      "inStock": 10,
      "filtered": 10
    },
    {
      "id": "7",
      "name": "FIFA 21",
      "serNum": "340825061",
      "price": 69.42,
      "manufacturer": "Electronics Arts",
      "category": "Playstation 5",
      "quantity": 18,
      "cartQuantity": 1,
      "image": "/assets/fifa21.jpg",
      "inStock": 10,
      "filtered": 10
    },
    {
      "id": "8",
      "name": "Super Smash Bros. Ultimate",
      "serNum": "419591143",
      "price": 57.99,
      "manufacturer": "Nintendo",
      "category": "Switch",
      "quantity": 11,
      "cartQuantity": 1,
      "image": "/assets/smashbros.jpg",
      "inStock": 10,
      "filtered": 10
    },
    {
      "id": "9",
      "name": "The Legend of Zelda: Breath of the Wild",
      "serNum": "700970794",
      "price": 49.99,
      "manufacturer": "Nintendo",
      "category": "Switch",
      "quantity": 7,
      "cartQuantity": 1,
      "image": "/assets/zelda.jpg",
      "inStock": 10,
      "filtered": 10
    },
    {
      "id": "10",
      "name": "Mario Kart 8 Deluxe",
      "serNum": "825782379",
      "price": 47.99,
      "manufacturer": "Nintendo",
      "category": "Switch",
      "quantity": 15,
      "cartQuantity": 1,
      "image": "/assets/mariokart.jpg",
      "inStock": 10,
      "filtered": 10
    },
    {
      "id": "11",
      "name": "Super Mario Odyssey",
      "serNum": "825782374",
      "price": 47.99,
      "manufacturer": "Nintendo",
      "category": "Switch",
      "quantity": 15,
      "cartQuantity": 1,
      "image": "/assets/marioodyssey.jpg",
      "inStock": 10,
      "filtered": 10
    },
    {
      "id": "12",
      "name": "Hades",
      "serNum": "825782329",
      "price": 47.99,
      "manufacturer": "Supergiant Games",
      "category": "Switch",
      "quantity": 15,
      "cartQuantity": 1,
      "image": "/assets/hades.jpg",
      "inStock": 10,
      "filtered": 10
    },
  ]
}